### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by bansawbanchee** [bradwestfall/mysql-chassis#28]
I do not see an option to utilize connection pooling. Is there an option to do this and if so can you provide an example?

Thanks!

**Comment by bradwestfall** [comment]
Hi @bansawbanchee, I was looking at how I designed the API and it seems as though I didn't provide  a way to use the mysqljs pooling API. I can work on that for the next version but don't know when I'll have that available.

**Comment by bradwestfall** [comment]
@bansawbanchee this feature has been added now
