### ISSUE TITLE
Add transaction support

### ISSUE THREAD

**Issue by iamvanja** [bradwestfall/mysql-chassis#29]
Chassis should have simple support for transactions based on https://github.com/mysqljs/mysql#transactions.

**Comment by bradwestfall** [comment]
Have you made progress with a Fork that I could see?

**Comment by iamvanja** [comment]
@bradwestfall https://github.com/iamvanja/mysql-chassis/blob/feature/transactions/src/index.js#L34-L37

It is a WIP as I'd like to find a nicer way to expose `this.connection` functionality coming from mysqljs. Declarations like this can easily go out of hand.

Also, they are still callback based and would like to promisify them on the fly. Something like `util.promisify` but with support for Node lower than version 8.

What do you think?

**Comment by therealklanni** [comment]
Auto-promise:

```js
function promisify(fn) {
  return function(...args) {
    return new Promise((resolve, reject) => {
      fn(...args, (err, ...resolveArgs) => {
        if (err) {
          reject(new Error(err))
        } else {
          resolve(...resolveArgs)
        }
      })
    })
  }
}
```

Just off the top of my head. Let me know if that doesn't work.

**Comment by iamvanja** [comment]
That worked, thanks @therealklanni. Submitting the PR now.
